### ISSUE TITLE
Persona

### ISSUE THREAD

**Issue by draarayan** [draarayan/Lernfel10-11#3]
Die   Persona enthält demographische Daten und Einblicke in die familiäre   Situation.

Bild der Person passt zur Beschreibung.

Die Einstellung der Person ist bspw. durch ein Zitat   klargestellt.

Informationen, die in Bezug zum Produkt relevant sind, werden   dargestellt und zeigen die entsprechenden Anforderungen auf.

**Comment by BenKunze** [comment]
[Persona.docx](https://github.com/user-attachments/files/16833721/Persona.docx)
